export const ARBITRUM_CHAIN_ID = 421614
export const BASE_CHAIN_ID = 84532
export const BSC_CHAIN_ID = 97
export const SCROLL_CHAIN_ID = 534351
export const SEPOLIA_CHAIN_ID = 11155111
export const DEFAULT_CHAIN_ID = ARBITRUM_CHAIN_ID
export const SUPPORTED_CHAIN_IDS = [ARBITRUM_CHAIN_ID, BASE_CHAIN_ID, BSC_CHAIN_ID, SCROLL_CHAIN_ID, SEPOLIA_CHAIN_ID]